### ISSUE TITLE
Interface to see test data?

### ISSUE THREAD

**Issue by danslo** [meertensm/bol-plaza-v2#1]
Your library works great. I just had a question: do you know if Bol.com offers a test environment for SDD?

I mean, I'm creating offers with the Test API but [this](https://www.bol.com/sdd/offers/offers.html?refresh=true) link won't show me offers (even though it says they were created).

**Comment by meertensm** [comment]
Hi,
They don't offer this. When you use test credentials everything you do goes into a blackhole, they actually force you to test in the live-environment.

**Comment by danslo** [comment]
Interesting... thanks for the reply!
