### ISSUE TITLE
ShipmentReference max lenght

### ISSUE THREAD

**Issue by timo002** [meertensm/bol-plaza-v2#11]
Hello,

I just wanted to create an issue for the max length of the ShipmentReference. But I noticed you just updated this issue. I don't know how this is coincidence that we ran into this issue at exactly the same time. But I was having issues with orders not being shipped according to Bol.com where we certainly shipped the orders to the customers. 

In my own code I change the ShipmentReference to the internal OrderId. This will also give a better overview on the bol.com/sdd overview page of all processed orders.

**Comment by meertensm** [comment]
Hi,
Changed it to your solution. Amazing coincidence indeed!
